// ==UserScript== 
// @name   贴吧展开
// @description  
// @match   tieba.baidu.com
// @require   file:///meta_res/1566672452.js
// @run-at   document-end
// ==/UserScript==


/* Automatically generated by the XBrowser TamperMonkey code adapter */
    var head = document.getElementsByTagName('body').item(0);
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src= 'https://greasyfork.org/scripts/377761-refuse-tieba-app-js/code/refuse-tieba-appjs.user.js';    head.appendChild(script);